### ISSUE TITLE
TypeError: Cannot read property 'repoName' of undefined

### ISSUE THREAD

**Issue by ljvmiranda921** [sbsends/cloud-build-badge#1]
I tried following your instructions but I seem to have an error in StackDriver that says:

```
TypeError: Cannot read property 'repoName' of undefined
```

Is it possible to have more verbose instructions so that people can easily follow? Thank you very much!

**Comment by samsends** [comment]
Hey @ljvmiranda921, I fixed that error, another bug, and made the instructions more verbose. Please let me know if this works. In StackDriver you should see `switched badge to build success` or `switched badge to build failure` along with execution notices.

**Comment by ljvmiranda921** [comment]
Hey @sbsends , 

I was able to make it work last night. Thanks! I noticed that `tensortask` was still included in the previous version, glad that it was now fixed! 

Great work! Will fork this repository to work with our specific use-case. Might also write some bit of tutorial (pointing to your repository) so that other people will know.

Closing this issue
